### ISSUE TITLE
[Solved] Using Devise with motion

### ISSUE THREAD

**Issue by davidalejandroaguilar** [unabridged/motion#19]
I'm trying Motion and View components for the first time, so I just copied and pasted a partial inside a component. This partial used inner partials that used Devise's `current_user`. When re-rendering it using Motion, it failed with:

```
21:00:24 web.1       |  Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
21:00:24 web.1       |  If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
```

I see this is happening because `current_user` defined by Devise [uses Warden's env](https://github.com/heartcombo/devise/blob/master/lib/devise/controllers/helpers.rb#L142-L144).

I noticed you had a (really helpful!) custom proc on the config file so I fixed this by doing the following:

```rb
  config.renderer_for_connection_proc = ->(websocket_connection) do
    ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'

    proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap do |proxy|
      proxy.set_user(
        websocket_connection.current_user,
        scope: :user,
        run_callbacks: false
      )
    end

    ApplicationController.renderer.new(
      websocket_connection.env.slice(
        Rack::HTTP_COOKIE,
        Rack::RACK_SESSION,
      ).merge('warden' => proxy)
    )
  end
```

I adapted the solution from [here](https://github.com/heartcombo/devise/issues/4271#issuecomment-636415714). I understand why I need it but not sure how this could be cleaned up a little so any pointers here are welcome.

It's worth mentioning that my `ApplicationCable::Connection` is `identified_by :current_user`. So that's why I could use `websocket_connection.current_user`.

**My question is:** Do you think this is something worth being added to the docs / wiki? If so, let me know and I'll be glad to open a PR. If not, maybe this issue would be enough for future Motion users.

**Comment by alecdotninja** [comment]
@davidalejandroaguilar I am open to adding a PR to add documentation.

I think you should be able to do something a bit simpler though:
```ruby
  config.renderer_for_connection_proc = ->(websocket_connection) do
    ApplicationController.renderer.new(
      websocket_connection.env.slice(
        Rack::HTTP_COOKIE,
        Rack::RACK_SESSION,
        'warden'
      )
    )
  end
```

Does that not work?

**Comment by alecdotninja** [comment]
If supporting it is as simple as including this additional env option, Warden is common enough that I would also be open to a PR to update the default `renderer_for_connection_proc` to include it. I don't want to allow everything by default because I'm not sure what all is safe to use on a long-lived and hijacked connection, but whitelisting individual keys like this should be fine.

**Comment by davidalejandroaguilar** [comment]
Ah, that also works. The `websocket_connection` object already has the warden environment, nice! 

I'll close this issue now. I'll open a PR for this default config change then. Thanks!
