### ISSUE TITLE
Updating a parent component within a child

### ISSUE THREAD

**Issue by davidalejandroaguilar** [unabridged/motion#22]
# Question

Side note: Sorry for opening an issue around this. Not sure if StackOverflow is monitored yet or what the best way to ask questions could be. Perhaps you could open a chat?

How would you re-render a component and the necessary children through a child action?

# Description

Given a parent/child component like this:

```rb
class PostListComponent < ViewComponent::Base
  include Motion::Component
  attr_reader :posts

  def initialize(posts:)
    @posts = posts
  end
end
```

```rb
class PostComponent < ViewComponent::Base
  include Motion::Component

  attr_reader :post

  def initialize(post:)
    @post = post
  end

  map_motion :update

  def update
    post.randomize_date_within!(5.days)
  end
end
```

```erb
<!-- post_list_component.html.erb -->
<div>
  <% posts.each do |post| %>
    <button data-motion="post_list_update" data-post-id="<%= post.id %>">PostListComponent#update</button>
    <%= render(PostComponent.new(post: post)) %>
  <% end %>
</div>
```

```erb
<!-- post_component.html.erb -->
<div>
  <div><%= post.title %></div>
  <div><%= post.date %></div>
  <div><%= content_tag :button, 'PostComponent#update', data: { motion: 'update' } %></div>
</div>
```

How would you setup your Motion components so that clicking the child's `PostComponent#update` button would re-render it's parent and thus the necessary (changed) children?

You can imagine that, for example, the child's button is marking a todo as "completed" and the task list would refresh to show the count of completed todo's.

# Reproduce the issue

I have created a demo repo [here](https://github.com/davidalejandroaguilar/motion_nested), it has a sqlite db so I think it should be ready to go. Else, just create a post. Clicking the `PostComponent#update` button should somehow trigger a `PostListComponent` re-render.

![img](https://i.imgur.com/CHhypKX.gif)

**Comment by alecdotninja** [comment]
As always, thank you for the very detailed and thoughtful issue, @davidalejandroaguilar .

In Motion, this is accomplished with [broadcasts](https://github.com/unabridged/motion#backend-interactions). I believe the strategy I described in #21 would solve this problem as well. 

> Side note: Sorry for opening an issue around this. Not sure if StackOverflow is monitored yet or what the best way to ask questions could be. Perhaps you could open a chat?

No worries. We don't currently have a better venue for asking questions, but that is something that I would be open to exploring. If you have any recommendations, let me know. In the meantime, please feel free to continue creating issues.

**Comment by sovapatr** [comment]
What about for a case where a broadcast doesn't make as much sense? Lets say I have an OrdersList component. And I would like to display a form component to edit an individual order when an edit button is pressed. So at the bottom of my OrdersListComponent I have:
`<%= render OrderFormComponent.new(order: @order) %>`

And in my OrderFormComponent I have something like 
`def render?
    @order.present?
  end`

From my OrderFormComponent I'd like to be able to set the parents `@order` object back to nil after clicking update or cancel and then rerender to have the form hidden again. Or am I just going about this the wrong way?

**Comment by alecdotninja** [comment]
@sovapatr In that case, I would hoist the state _out_ to the `OrderFormComponent` component and make `OrdersList` component [presentational](https://medium.com/@yassimortensen/container-vs-presentational-components-in-react-8eea956e1cea). In Motion, this corresponds to *not* including `Motion::Component`.

I think this will also work well for this use-case because it will let you keep all of the state within the `Order` model and have a form for it.

**Comment by alecdotninja** [comment]
@sovapatr That's an interesting use-case that I will have to think more about. As it stands right now, you _must_ use broadcasts to communicate from the child to the parent, but I agree this is a little awkward here.

There might be a way to structure the components so that this communication is not necessary, but I feel like that is beside the point of your question.

In general, you can do something like this:

```ruby
class ParentComponent < ApplicationComponent
  include Motion::Component

  # Pass this down to the child component so that it can contact you after it is rendered
  attr_reader :callback_topic

  def initialize
     @callback_topic = SecureRandom.uuid

     # Listen for a message from the child component
     stream_from callback_topic, :callback
  end

  def callback(data)
    # This method can be triggered with `ChildComponent#trigger_callback_on_parent`
  end
end

class ChildComponent < ApplicationComponent
  include Motion::Component

  def initialize(callback_topic:)
    @callback_topic = callback_topic
  end

  def trigger_callback_on_parent(data)
    ActionCable.server.broadcast(@callback_topic, data)
  end
end
```

If you are willing to put up some code, I am happy to take a look at your specific case.

**Comment by alecdotninja** [comment]
@sovapatr An abstraction like this might make this a bit easier to manage. I'm still playing around with the details. Let me know what you think for your use-case:

```ruby
# frozen_string_literal: true

class Callback
  attr_reader :broadcast

  def initialize
    @broadcast = "motion:callback:#{SecureRandom.uuid}"
  end

  def bind(component, method)
    component.stream_from(broadcast, method)
  end

  def call(data)
    ActionCable.server.broadcast(broadcast, data)
  end
end
```

**Comment by sovapatr** [comment]
Thank you for the suggestions. I ended up removing the `include Motion::Component` from the inner component and moved the `map_motion` functions to the parent. This is going to work perfectly for my current use case. Though I will keep in mind these callback suggestions. I could see needing them if I required more logic in the child component such as validations and wanted to split it back up.
