### ISSUE TITLE
Consider changing the name?

### ISSUE THREAD

**Issue by andrewhavens** [unabridged/motion#29]
Hello! Looks like you have a great project here. I'm looking forward to using it!

I just wanted to make you aware, if you didn't already know, that the name "motion" is already very popular in the Ruby world. There is a tool called [RubyMotion](http://www.rubymotion.com) and its command line tool is called `motion` and most of the gems related to RubyMotion are either prefixed with `motion-` ([RubyGems search](https://rubygems.org/search?utf8=✓&query=motion-)) and/or are under the `Motion` namespace.

I bring this up simply to help you to consider avoiding potential confusion or naming conflicts in the future. Keep up the great work!

**Comment by latortuga** [comment]
Hi there @andrewhavens 👋 , thanks for the feedback! We are aware of RubyMotion and considered different options but ultimately settled on Motion for a couple of reasons:

- "RubyMotion" is one word as stated by the authors, and is not referred to as "motion". CLI notwithstanding, the technology is always called RubyMotion.
- "Motion" was not taken in the rubygem or JS ecosystem, and is a great name. It's short and makes for expressive API methods and terminology.

The `Motion` namespace is not something we had considered but I don't think it will be problematic at this point. RubyMotion is a toolkit for building mobile apps, our gem is targeted at Rails apps. These likely won't ever coexist.

At this time we are not considering changing the name and we are comfortable with it being similar.

**Comment by andrewhavens** [comment]
No worries! Just wanted to let you know. Keep up the great work.

**Comment by bbugh** [comment]
It took me 15 minutes to find this gem! I had to dig through my reddit history. Everything in all of the search results are Ruby Motion. This gem is awesome but I think it was a big mistake to name it the same as an existing and prolific Ruby system. I hope that you reconsider ;)
